<a href="https://colab.research.google.com/github/haneefSaeed/C-Sharp/blob/master/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

## cuda version 12. 6

2.9.0+cu126


In [ ]:
!nvidia-smi

## does not work until on GPU


/bin/bash: line 1: nvidia-smi: command not found


## Tensors
* Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim, scalar.shape, scalar.size(), scalar.device, scalar.dtype

(0, torch.Size([]), torch.Size([]), device(type='cpu'), torch.int64)

In [ ]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
MATRIX = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,0], [1,2,3]], [[0, 1 , 2], [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 0],
         [1, 2, 3]],

        [[0, 1, 2],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim, TENSOR.shape, TENSOR.size()

(3, torch.Size([3, 2, 3]), torch.Size([3, 2, 3]))

In [ ]:
TENSOR[0], TENSOR[0][0], TENSOR[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
# TENSOR Parameters
#. dtype = chk docs int32 int16, float16, 32, 64,
#. device = can be gpu or cpu or tpu
#. require grad = is required gradiant tracking
randomTensor = torch.rand([2,2,2], dtype=torch.float32, device='cpu', requires_grad=False)
randomTensor

tensor([[[0.4400, 0.5536],
         [0.3248, 0.6503]],

        [[0.7962, 0.1199],
         [0.8425, 0.5119]]])

In [ ]:
# Randoms , zeros, ones, range

zeros = torch.zeros([3,3], dtype=torch.int32)
zeros

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [ ]:
ones = torch.ones([3,3], dtype=torch.float32)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# like copy from another array size
onesLikeZeros = torch.ones_like(zeros)
onesLikeZeros

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
randLikeOnes = torch.rand_like(ones)
randLikeOnes

tensor([[0.5144, 0.1088, 0.5056],
        [0.1984, 0.0235, 0.0808],
        [0.1480, 0.0884, 0.4867]])

In [ ]:
rangeTensor = torch.arange(0, 10, dtype=torch.float32)
rangeTensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
zeroTo1000 = torch.arange(0,1000, 10)
zeroTo1000

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

## Tensor Operations
* Addition
* Subtraction
* Multiplication
* Mat Mul
* Division

In [ ]:
tenOne = torch.tensor([2,4])
tenTwo = torch.tensor([5,8])
tenOne, tenTwo

(tensor([2, 4]), tensor([5, 8]))

In [ ]:
# using normal operation
tenOne+tenTwo, tenTwo-tenOne, tenTwo/tenOne, tenOne*tenTwo

(tensor([ 7, 12]), tensor([3, 4]), tensor([2.5000, 2.0000]), tensor([10, 32]))

In [ ]:
# using torch functions
torch.add(tenOne, tenTwo), torch.sub(tenTwo, tenOne), torch.mul(tenTwo, tenOne), torch.div(tenTwo, tenOne)

(tensor([ 7, 12]), tensor([3, 4]), tensor([10, 32]), tensor([2.5000, 2.0000]))

In [ ]:
matOne , matTwo = torch.tensor([[2,3], [4,5], [6,7]]), torch.tensor([[1,1], [2,2]])
matOne, matTwo, matOne.shape, matTwo.shape


(tensor([[2, 3],
         [4, 5],
         [6, 7]]),
 tensor([[1, 1],
         [2, 2]]),
 torch.Size([3, 2]),
 torch.Size([2, 2]))

In [ ]:
#chck notes for matrix multiplication

torch.matmul(matOne, matTwo)

tensor([[ 8,  8],
        [14, 14],
        [20, 20]])

In [ ]:
# matrix transpose
matOne.T

tensor([[2, 4, 6],
        [3, 5, 7]])

In [ ]:
## min max avg operation
ztt = torch.arange(10, 200, 10)
ztt, ztt.dtype

(tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
         150, 160, 170, 180, 190]),
 torch.int64)

In [ ]:
ztt.min(), ztt.max(), torch.min(ztt) ## can be written in 2 ways

(tensor(0), tensor(190), tensor(0))

In [ ]:
ztt.mean(dtype=torch.float64)

tensor(95., dtype=torch.float64)

In [ ]:
ztt.sum(), torch.sum(ztt)

(tensor(1900), tensor(1900))

In [ ]:
# argmin
ztt.argmin()

tensor(0)

In [ ]:
ztt[0]

tensor(10)

In [ ]:
ztt.argmax()

tensor(18)

In [ ]:
ztt[18]

tensor(190)

## SHAPE MANIPULATION


In [ ]:
rangten = torch.arange(1,10, dtype=torch.float32)
rangten, rangten.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
 # Reshapping (Add Dimension)
 rangten_reshape = rangten.reshape(1, 9)
 rangten_reshape2 = rangten.reshape(9,1 )

#  rangten_invalidShape = rangten.reshape(2,1)
 rangten_reshape, rangten_reshape.shape, rangten_reshape2, rangten_reshape2.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

### The Tensor View is same as reshape except it shares the same memory

In [5]:
b = torch.arange(1,10)
b

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
c = b.view(1,9)
c

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
# change in c results in change in b
c[:,0]=12
b,c

(tensor([12,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([[12,  2,  3,  4,  5,  6,  7,  8,  9]]))

In [19]:
cstack= torch.stack([c,c])
cstack, cstack.shape

(tensor([[[12,  2,  3,  4,  5,  6,  7,  8,  9]],
 
         [[12,  2,  3,  4,  5,  6,  7,  8,  9]]]),
 torch.Size([2, 1, 9]))

In [10]:
chstack = torch.hstack([c, c])
chstack

tensor([[12,  2,  3,  4,  5,  6,  7,  8,  9, 12,  2,  3,  4,  5,  6,  7,  8,  9]])

In [16]:
cvstack=torch.vstack([c,c, c, c , b ])
cvstack, cvstack.shape

(tensor([[12,  2,  3,  4,  5,  6,  7,  8,  9],
         [12,  2,  3,  4,  5,  6,  7,  8,  9],
         [12,  2,  3,  4,  5,  6,  7,  8,  9],
         [12,  2,  3,  4,  5,  6,  7,  8,  9],
         [12,  2,  3,  4,  5,  6,  7,  8,  9]]),
 torch.Size([5, 9]))

## SQUEEZE

You have this:
`[1, 2, 3]`        → shape `[3]`

`unsqueeze(0)` wraps it inside another list:
`[[1, 2, 3]]`      → shape `[1, 3]`

`unsqueeze(1)` makes each element its own box:
`[[1], [2], [3]]`  → shape `[3, 1]`

`squeeze()` removes all “pointless” dimension boxes:
`[[1, 2, 3]]`  → squeeze → `[1, 2, 3]`

In [30]:
lst = torch.tensor([1,2,3])
lst, lst.shape

(tensor([1, 2, 3]), torch.Size([3]))

In [44]:
lst = torch.unsqueeze(lst, 0)

In [45]:
lst, lst.shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [46]:
lst = torch.squeeze(lst, )

In [47]:
lst, lst.shape

(tensor([1, 2, 3]), torch.Size([3]))

## PERMUTE
Used mostly in images

Example:
Drawer[Type][Color][Size]
Example shape:
[3 types, 4 colors, 2 sizes] → shape (3, 4, 2)
If you call: drawer.permute(1, 0, 2), It means:
now organize as:
Drawer[Color][Type][Size]




In [67]:
# example

img = torch.rand(3, 4, 5)
img, img.shape

(tensor([[[0.4564, 0.1404, 0.3483, 0.5317, 0.1750],
          [0.4704, 0.2450, 0.1368, 0.4096, 0.4133],
          [0.7411, 0.2572, 0.2178, 0.1469, 0.7317],
          [0.3448, 0.9982, 0.4666, 0.6844, 0.2416]],
 
         [[0.0349, 0.7456, 0.1394, 0.4610, 0.3563],
          [0.3468, 0.2950, 0.9908, 0.2379, 0.4509],
          [0.9210, 0.9631, 0.9102, 0.8741, 0.6874],
          [0.2706, 0.8391, 0.0900, 0.9719, 0.2011]],
 
         [[0.5099, 0.7674, 0.9385, 0.0986, 0.9813],
          [0.2057, 0.0357, 0.5074, 0.3965, 0.1943],
          [0.6660, 0.6906, 0.6828, 0.7775, 0.9145],
          [0.3934, 0.6872, 0.0114, 0.1804, 0.2077]]]),
 torch.Size([3, 4, 5]))

In [69]:
img_hwcn = img.permute(1,2,0) ## index 2 => 5, 1=>4 , 0 => 3, we can rearrange
img_hwcn, img_hwcn.shape

(tensor([[[0.4564, 0.0349, 0.5099],
          [0.1404, 0.7456, 0.7674],
          [0.3483, 0.1394, 0.9385],
          [0.5317, 0.4610, 0.0986],
          [0.1750, 0.3563, 0.9813]],
 
         [[0.4704, 0.3468, 0.2057],
          [0.2450, 0.2950, 0.0357],
          [0.1368, 0.9908, 0.5074],
          [0.4096, 0.2379, 0.3965],
          [0.4133, 0.4509, 0.1943]],
 
         [[0.7411, 0.9210, 0.6660],
          [0.2572, 0.9631, 0.6906],
          [0.2178, 0.9102, 0.6828],
          [0.1469, 0.8741, 0.7775],
          [0.7317, 0.6874, 0.9145]],
 
         [[0.3448, 0.2706, 0.3934],
          [0.9982, 0.8391, 0.6872],
          [0.4666, 0.0900, 0.0114],
          [0.6844, 0.9719, 0.1804],
          [0.2416, 0.2011, 0.2077]]]),
 torch.Size([4, 5, 3]))

# INDEXING  

In [6]:
x = torch.arange(1, 10).reshape(1, 3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [7]:
# indexing basics

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [8]:
x[0][0]

tensor([1, 2, 3])

In [9]:
x[0][2][2]

tensor(9)

In [11]:
x[: , 0], x[:,0].shape

(tensor([[1, 2, 3]]), torch.Size([1, 3]))

In [29]:
y = torch.arange(1,201).reshape(2, 25, 4)

In [31]:
y, y.shape

(tensor([[[  1,   2,   3,   4],
          [  5,   6,   7,   8],
          [  9,  10,  11,  12],
          [ 13,  14,  15,  16],
          [ 17,  18,  19,  20],
          [ 21,  22,  23,  24],
          [ 25,  26,  27,  28],
          [ 29,  30,  31,  32],
          [ 33,  34,  35,  36],
          [ 37,  38,  39,  40],
          [ 41,  42,  43,  44],
          [ 45,  46,  47,  48],
          [ 49,  50,  51,  52],
          [ 53,  54,  55,  56],
          [ 57,  58,  59,  60],
          [ 61,  62,  63,  64],
          [ 65,  66,  67,  68],
          [ 69,  70,  71,  72],
          [ 73,  74,  75,  76],
          [ 77,  78,  79,  80],
          [ 81,  82,  83,  84],
          [ 85,  86,  87,  88],
          [ 89,  90,  91,  92],
          [ 93,  94,  95,  96],
          [ 97,  98,  99, 100]],
 
         [[101, 102, 103, 104],
          [105, 106, 107, 108],
          [109, 110, 111, 112],
          [113, 114, 115, 116],
          [117, 118, 119, 120],
          [121, 122, 123, 124],
     

In [36]:
y[1, 2, 2] , y[0, 1, 0], y[: , 1, 0], y[1, :, 2]

(tensor(111),
 tensor(5),
 tensor([  5, 105]),
 tensor([103, 107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
         159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199]))

# NUMPY and TORCH

In [43]:
arr = np.arange(0, 20, 2)

tens = torch.from_numpy(arr)

arr, tens

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [45]:
tentoarr = torch.ones(7)
nparr = tentoarr.numpy()
tentoarr, nparr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# RANDOOM SEED

In [6]:
SEED = 40

torch.manual_seed(SEED)
r = torch.rand([3,3])

r2 = torch.rand([3,3])

torch.manual_seed(SEED)
r2 = torch.rand([3,3])
r, r2, r==r2


(tensor([[0.3679, 0.8661, 0.1737],
         [0.7157, 0.8649, 0.4878],
         [0.5501, 0.1318, 0.2897]]),
 tensor([[0.3679, 0.8661, 0.1737],
         [0.7157, 0.8649, 0.4878],
         [0.5501, 0.1318, 0.2897]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

# GPU RUNTIME

In [1]:
!nvidia-smi


Tue Dec  9 20:58:07 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
torch.cuda.is_available()

True

In [6]:
# setup device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [8]:
dten = torch.tensor([2,3,3])
dten, dten.device

(tensor([2, 3, 3]), device(type='cpu'))

In [9]:
dtengpu = torch.tensor([4,5,5], device='cuda')
dtengpu

tensor([4, 5, 5], device='cuda:0')

In [11]:
tenToGpu = dten.to('cuda')
tenToGpu

tensor([2, 3, 3], device='cuda:0')

In [17]:
# gpu tensor on numpy
cpuTensor = dtengpu.cpu()
cpuTensor.numpy()

tenToCPU = dten.to('cpu')

cpuTensor



tensor([4, 5, 5])